#!/usr/bin/env bash

# 
# bash_utils
# 
# Summary:
# 
#     Generic constants and utilities to be sourced by other scripts 
# 
# References:
# 
#     (Noted next to each utility)
#     

# --------------------------------------------
# Constants
# --------------------------------------------

# Colors
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
G="\033[1;32m" # Green
GY="\033[1;37m" # Gray
Y="\033[1;93m" # Yellow 
R="\033[1;31m" # Red
BLD="\033[1;1m" #BOLD
N="\033[0m" # ~reset~

INV="\033[1;7m" # Inverse
CODE="\033[1;93;100m" # Fill Dark Gray

# Icons
ICON_INFO="${BLD}\xE2\x84\xB9 INFO:${N}"
ICON_POSITIVE="${G}\xE2\x9C\x94 SUCCESS:${N}"
ICON_WARNING="${Y}\xE2\x9A\xA0 WARNING:${N}"
ICON_NEGATIVE="${R}\xE2\x9C\x98 FAILED:${N}"
ICON_MUGS="${Y}\xF0\x9F\x8D\xBB CHEERS!:${N}"


# Data
MB=1048576


# SourceTree output doesn't support bash colors or icons.
_string=$PYTHONPATH
_substring="SourceTree"
if test "${PYTHONPATH#*$_substring}" != "$PYTHONPATH"
    then
    # SourceTree Detected.  Remove bash styling for cleaner output.
    G=""
    GY=""
    Y=""
    R=""
    BLD=""
    N=""
    INV=""
    CODE=""
    ICON_INFO=""
    ICON_POSITIVE=""
    ICON_WARNING=""
    ICON_NEGATIVE=""
    ICON_MUGS=""
fi


# --------------------------------------------
# Functions
# --------------------------------------------


# http://stackoverflow.com/questions/4023830/how-compare-two-strings-in-dot-separated-version-format-in-bash
# 0 : =
# 1 : >
# 2 : <
vercomp () {
    if [[ $1 == $2 ]]
    then
        echo 0
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            echo 1
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            echo 2
            return 2
        fi
    done
    echo 0
    return 0
}


vercomp_char () {
    local op
    case $1 in
        0) op='=';;
        1) op='>';;
        2) op='<';;
    esac
    echo $op
}


testvercomp () {
    vercomp $1 $2
    if [[ $(vercomp_char $?) != $3 ]]
    then
        # echo "FAIL: Expected '$3', Actual '$op', Arg1 '$1', Arg2 '$2'"
        echo 1
        return 1
    else
        # echo "Pass: '$1 $op $2'"
        echo 0
        return 0
    fi
}



# http://stackoverflow.com/questions/39576257/how-to-limit-file-size-on-commit
# https://stackoverflow.com/questions/6879501/filter-git-diff-by-type-of-change
list_new_or_modified_files()
{
    git diff --cached --name-only --diff-filter=AM
}

# https://stackoverflow.com/questions/6879501/filter-git-diff-by-type-of-change
list_tracked_modified_files()
{
    git diff --name-only --diff-filter=AM
}



# Lists untracked files, which are shouldn't be ignored
# https://stackoverflow.com/questions/17358953/how-to-make-a-list-of-all-the-cached-files-and-untracked-files-in-a-git-reposito
list_untracked_files()
{
    git ls-files --others --exclude-standard
}


# Remove leading and trailing double quotes
unmunge()
{
    local result="${1#\"}"
    result="${result%\"}"
    echo "$result"
}


# Check filesize for all staged files
#   Return: > 0 if hard_limit is breached
check_file_size()
{
    hard_limit=$1
    soft_limit=$2
    ext_ignore_list=("${@:3}") # argument list, removing first 2
    hard_limit_human=$(echo $hard_limit| awk '{ foo = $1 / 1024 / 1024 ; print foo "MB" }')
    soft_limit_human=$(echo $soft_limit| awk '{ foo = $1 / 1024 / 1024 ; print foo "MB" }')
    n=0

    # validate first 2 arguments as numbers
    re='^[0-9]+$'
    if ! [[ $1 =~ $re ]] ; then
       echo -e "   $ICON_NEGATIVE Provided hard_limit \"${1}\" not valid" >&2; exit 1
    fi
    if ! [[ $2 =~ $re ]] ; then
       echo -e "   $ICON_NEGATIVE Provided soft_limit \"${2}\" not valid" >&2; exit 1
    fi

    while read -r munged_filename
    do
        f=$(unmunge "$munged_filename")
        h=$(git ls-files -s "$f"|cut -d' ' -f 2)
        s=$(git cat-file -s "$h")
        s_human=$(echo $s| awk '{ foo = $1 / 1024 / 1024 ; print foo "MB" }')
        filename=$(basename "$f")
        ext="${filename##*.}"

        # Ignore needed exts
        if [[ " ${ext_ignore_list[@]} " =~ " ${ext} " ]]; then
            echo -e "      $ICON_INFO Size check ignored for ${filename}"
            continue
        fi
        
        # Count files that exceed the given limits
        if [ "$s" -gt $hard_limit ]
        then
            echo -e "   $ICON_NEGATIVE Exceeded hard size limit ($hard_limit_human): $munged_filename ($s_human)"
            echo -e "      $ICON_INFO You must track this extension. Run ${CODE} git lfs track \"*.${ext}\" ${N} before proceeding."
            n=$((n+1))
        elif [ "$s" -gt $soft_limit ]
        then
            echo -e "   $ICON_WARNING Exceeded soft size limit ($soft_limit_human): $munged_filename ($s_human)"
            echo -e "      $ICON_INFO Please consider tracking this extension using ${CODE} git lfs track \"*.${ext}\" ${N}"
        fi
    done

    return $n
}

# string_contains(string, substring)
#
# Returns 0 if the specified string contains the specified substring,
# otherwise returns 1.
string_contains() {
    string="$1"
    substring="$2"
    if test "${string#*$substring}" != "$string"
    then
        return 0    # $substring is in $string
    else
        return 1    # $substring is not in $string
    fi
}


# http://stackoverflow.com/questions/8063228/how-do-i-check-if-a-variable-exists-in-a-list-in-bash
contains() {
    [[ "$1" =~ (^|[[:space:]])"$2"($|[[:space:]]) ]] && return 0 || return 1
}


# https://stackoverflow.com/questions/3685970/check-if-a-bash-array-contains-a-value
array_contains () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}


# Backup File
backup_file () {
    filename=$1
    filetime=$(date +%Y%m%d_%H%M%S)

    if cp ${filename} ${filename}_${filetime}
    then
        echo -e "${ICON_POSITIVE} Backup created: ${filename} -> ${filename}_${filetime} ${N}"
    else
        echo -e "${ICON_NEGATIVE} Backup failed: ${filename}"
    fi
}
