#!/usr/bin/env bash

# 
# install-merge-tools
# 
# Summary:
# 
#     This script helps a user install Unity's "UnityYAMLMerge" tool for use in
#     a local git repo's merging actions.
#     
#     This script also installs the merge tool for SourceTree
# 
# 
# References:
# 
#     - https://docs.unity3d.com/Manual/SmartMerge.html
#     - http://kihira.uk/unity-and-git-getting-them-to-play-nicely/
#     - https://gist.github.com/Ikalou/197c414d62f45a1193fd
#     

# Import Dependencies
#   - paths must be relative to the git repo's root path
DIR=$(git rev-parse --show-toplevel)
if [[ ! -d "$DIR" ]]
then
    echo "Error: Git repo was not found."
    exit;
else
    source "$DIR/utils/bash_utils"
fi



echo -e "${BLD}------------------------------------------------------${N}"
echo -e "${BLD}     Hack and Paint [UnityYAMLMerge Installation]     ${N}"
echo -e "${BLD}------------------------------------------------------${N}"

echo -e "${BLD}Install Git Merge Tools/Settings for Unity...${N}"
echo -e "- Now searching for available merge tool paths... (this may take a few seconds)"



# Detect OS
ROOT_SEARCH_PATHS=""
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    # Ask linux users to provide a root path
    echo -n -e "${BLD}Please enter a root path to search for your Unity application and press [ENTER]: ${N}"
    read ROOT_SEARCH_PATHS
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    ROOT_SEARCH_PATHS="/Applications"
# elif [[ "$OSTYPE" == "cygwin" ]]; then
#     # POSIX compatibility layer and Linux environment emulation for Windows
elif [[ "$OSTYPE" == "msys" ]]; then
    # Lightweight shell and GNU utilities compiled for Windows (part of MinGW) & Windows GitBash
    # Search for available drives on GitBash Windows
    ROOT_SEARCH_PATHS=$(cat /proc/partitions | awk '{print $5}' | grep -e "[A-Z][:]" | tr ':\\' ' ' | sed -e "s/[[:space:]]\+/ /g" | awk '{print "\"/"$1"\""}' | tr '\n' ' ')
# elif [[ "$OSTYPE" == "win32" ]]; then
#     # I'm not sure this can happen.
# elif [[ "$OSTYPE" == "freebsd"* ]]; then
#     # ...
else
    echo -e "${icon_negative} "${OSTYPE}" is not a recognized OS"
fi

# Backup File
backup_file () {
    filename=$1
    filetime=$(date +%Y%m%d_%H%M%S)

    if cp ${filename} ${filename}_${filetime}
    then
        echo -e "${icon_positive} Backup created: ${filename} -> ${filename}_${filetime} ${N}"
    else
        echo -e "${icon_negative} Backup failed: ${filename}"
    fi
}




# -------------------------------------------------
# Actions
# -------------------------------------------------

# a) Find available UnityYAMLMerge tool paths
COUNTER=0
declare -a FOUND_PATHS
echo ""
while read found_path
do
    FOUND_PATHS[$COUNTER]=${found_path}
    echo "  ${COUNTER}) ${found_path}"
    COUNTER=$((COUNTER + 1))
done< <(find $ROOT_SEARCH_PATHS -name "UnityYAMLMerge*" 2>/dev/null)
echo ""


# b) Ask user to choose path
echo -n -e "${BLD}Enter the number of the path you would like to use and press [ENTER]: ${N}"
read tool_path_index
CHOSEN_TOOL_PATH=${FOUND_PATHS[$tool_path_index]}
echo -e "${icon_positive} You've chosen the path \"$CHOSEN_TOOL_PATH\""


# c) Install Path Settings
if [[ -x ${FOUND_PATHS[$tool_path_index]} ]]
then
    # Create a backup of the user's gitconfig file
    backup_file ".git/config"

    git config --local merge.tool unityyamlmerge
    git config --local mergetool.unityyamlmerge.trustExitCode false
    git config --local mergetool.unityyamlmerge.keepTemporaries true
    git config --local mergetool.unityyamlmerge.keepBackup false
    git config --local mergetool.unityyamlmerge.path "${CHOSEN_TOOL_PATH}"
    git config --local mergetool.unityyamlmerge.cmd "\"${CHOSEN_TOOL_PATH}\" merge -p \"\$BASE\" \"\$REMOTE\" \"\$LOCAL\" \"\$MERGED\""
    git config --local mergetool.sourcetree.cmd "\"${CHOSEN_TOOL_PATH}\" merge -p \"\$BASE\" \"\$REMOTE\" \"\$LOCAL\" \"\$MERGED\""
    git config --local mergetool.sourcetree.trustexitcode true
    echo -e "${icon_positive} .git/config Updated${N}"
else
    echo -e "${icon_negative} Given path was not executable. Git Config not updated properly."
    exit;
fi

echo -e "${icon_mugs} Install Complete!"

echo -e ""
echo -e "${INV} Consider re-running this script if you ever change your Unity version. ${N}"
echo -e ""
